### ISSUE TITLE
What are all the ways to get my userID?

### ISSUE THREAD

**Issue by TheRealJeku** [thenickdude/PlanC#19]
Hello and thank you for making this tool!  

I have an old CP archive from 2015 but I no longer have the software installed on the computer, so sadly no adb file.  Also my properties file doesn't have any indication of a secret key.  I notice you updated a way to derive the key with the userID and my archive password.  There's about 10 passwords that could be a possibility, but I'm not sure how to get the userID.  Is the user ID the number in the path to the archive?  i.e. /658668002747.... where the files are?  I've noticed this number is reused in every single folder in the archive.  I also tried using the number in my old credit card records but that is probably the company phone number.

There's also a value in the properties file called `targetGuid`... could that be it?

Thanks!

**Comment by thenickdude** [comment]
No, the number in the backup path is the backup GUID. The user ID is a small integer like 12502. The CrashPlan log files mention it frequently so search those for userId if you have any left (they're in the CrashPlan app directory rather than in the backup path). It might be found elsewhere but that's the only place I know of at the moment. 

Deriving the encryption key from a password is only applicable if you configured CrashPlan to use a custom encryption key derived from a passphrase, described here:

https://support.code42.com/CrashPlan/6/Configuring/Upgrade_Code42_app_security_to_custom_key ([archive.org archive](https://web.archive.org/web/20210118164617/https://support.code42.com/CrashPlan/6/Configuring/Upgrade_Code42_app_security_to_custom_key))

If you used the default CrashPlan settings then the encryption key was fully random and doesn't relate to your password.

**Comment by TheRealJeku** [comment]
Thanks for the information.  I definitely didn't trust CP with my data so I would have opted to use my own encryption key.  I haven't had this software installed for many years so I was hoping there was another way to get my user ID, maybe with one of those files in the root of the archive.  I could always send Code 42 an email but since I'm unable to login to my account, they probably have deleted my user record by now.

**Comment by thenickdude** [comment]
Can you confirm what value securityKeyType has in the cp.properties file in the backup?

**Comment by TheRealJeku** [comment]
Yes, that is set to `PrivatePassword`

But the problem I have is getting my userID because I'm fairly sure I can come up with the password I used.  Thanks again!

**Comment by thenickdude** [comment]
I think your userID could be brute-forced actually. Each key generated requires 100,000 SHA-1 iterations, which is feasible.

Your cp.properties has a dataKeyChecksum, right? This is a simple MD5 sum of the final encryption key which can be used to check if generation succeeded.

**Comment by thenickdude** [comment]
Please try out my new release 0.2.1, it supports brute-forcing the user ID. You'll need to add a "--cpproperties" argument to the derive-key commandline that points to the cp.properties file in your backup:

https://github.com/thenickdude/PlanC/releases/tag/v0.2.1

**Comment by TheRealJeku** [comment]
This is awesome, thank you!  I checked and I have a `dataKeyChecksum` so I will be testing your new version today!  I'll let you know how this goes!

**Comment by TheRealJeku** [comment]
I'm brute-forcing a bunch of different password options.  If there's a backslash in the password, do I need to put the password in double-quotes and escape (backslash) the backslash?  Hope I'm making sense!

**Comment by thenickdude** [comment]
Nah, you don't need to apply any escaping or quoting.

**Comment by TheRealJeku** [comment]
I found the password to the archive in an old passwords location and the brute force tool still failed.  I wonder if it's possible that my user ID is above the 100,000 limit of the tool?  I would like to also note that my password has some special characters but you had said earlier that they shouldn't need to be double-quoted or escaped.

**Comment by thenickdude** [comment]
Ahh, I missed a zero, the 100,000 limit is way too low, even my user ID is in the 300,000s. I've pushed a new release now that searches up to 1 million, please try that:

https://github.com/thenickdude/PlanC/releases/tag/v0.2.1

I joined CrashPlan in March 2012, how about you?

Edit: I found this log file someone posted to the net and their ID was nearly 3 million:

https://webcache.googleusercontent.com/search?q=cache:okroL0j8_J0J:https://www.ixsystems.com/community/attachments/serivice-log-0-txt.8877/+&cd=10&hl=en&ct=clnk&gl=nz

**Comment by thenickdude** [comment]
Ahh hang on, I think PrivatePassword is actually when CrashPlan randomly generated a key and then encrypts that key with your password. In that case you still need to find the encrypted key to decrypt with your password, you can't generate it from nothing.

Can you email me your cp.properties file just in case there's something useful in there I can spot? n.sherlock@gmail.com

**Comment by TheRealJeku** [comment]
Sure thing!  I'll send it over right now.  Anything that can assist you better is good with me :)

**Comment by thenickdude** [comment]
I was hoping there would be some key in there, but it looks like there isn't. Sorry, I don't think your backup can be recovered unless you can find your old adb directory.

**Comment by TheRealJeku** [comment]
Oh no, that's too bad.  But if I were to somehow get my userID from somewhere or even Code 42 (doubtful), would I still be able to recover the files through the way that doesn't involve the old adb directory?

**Comment by thenickdude** [comment]
Nope, sorry. Since your backup was encrypted with a random escrowed encryption key generated by Code42 (which was then further encrypted with your password), your backup cannot be recovered without getting that random key back. It would have been silly for Code42 to hold onto these keys after the shutdown date, because they only represented a security risk at that point. If they did retain those keys, you'd probably have to force your key out of them with legal action.

If you still have the disk that had your ADB directory on it, and that disk had File Versions / File History turned on, the ADB directory might still be available. But I don't think that is enabled by default. Did you double check that none of the ADB locations existed?

C:\ProgramData\CrashPlan\conf\adb or C:\Users\<username>\AppData\<Local or Roaming>\CrashPlan\conf\adb
