### ISSUE TITLE
Recover Backup from cp.properties

### ISSUE THREAD

**Issue by StoneNimRod** [thenickdude/PlanC#20]
Hello, many years ago my family had a crash plan home account where we used to backup photos. In 2018 I tried to recover a backup without any results. Yesterday we were talking about the backup and now I'm here.
Now, I have a backup folder containing the cp.properties file and it contains the secureDataKey, dataKeyChecksum and userPassword. 
I don't remember the password we used at that time. Is there any way to recover the backup photos?
Thank you

**Comment by thenickdude** [comment]
I'm pretty sure recovery is impossible if you don't know the password, since the archive encryption key is itself encrypted by the password.

Do you remember if you used that same password on any other internet services? Maybe one of them was hacked and the password leaked to the world, and you can retrieve the password that way.

**Comment by thenickdude** [comment]
You might be able to recover the password by brute-force attack if it was short, do you know how long it was?

Also if you still have any other files, like the Crashplan program files itself, or especially the "adb" directory mentioned here that would be a big help:

https://github.com/thenickdude/PlanC#decryption-keys

**Comment by StoneNimRod** [comment]
Okey, I don't recall but prob. it was a standard password that we used for other services. 
I think it would be quite long as the passwords we used have at most 10 chars. 

The Crashplan files are lost as the pc we used at that time is broken.

Is there any way to get the password from the userPassword entry? It is a string with: (27chars)  \=\:  (11chars)  \=

Thank you

**Comment by thenickdude** [comment]
That userPassword entry was written by an older version of CrashPlan (the final version they released never wrote that field), so I'll have to dig up an old version to discover how the password was encoded to know if it could be recovered from there. 

Since your password was long, a brute force recovery is unlikely to be possible. It'd be more likely for you to guess passwords yourself I think using plan C to check the guesses against the cp.properties file

**Comment by StoneNimRod** [comment]
Ah, okey no problem. Yes, I'm trying to guess the password by checking if it can decode the dataKey. Thanks

**Comment by thenickdude** [comment]
I checked out how that UserPassword hash is constructed, and I think it'll be infeasible to crack that for a length-10 password. 

For a length-8 password of only lowercase letters and numbers, I think it could be recovered for around 50-300 USD. 

For a length-10 password I think it'd cost more like 50,000 USD.

**Comment by thenickdude** [comment]
If you email me your cp.properties file I can try cracking the password using a public password list for you, since that'll only take a couple of hours on my PC. ( n.sherlock@gmail.com )

However any more in-depth cracking (e.g. for passwords that were only random characters) will require some rented server time though like I mentioned before.

**Comment by thenickdude** [comment]
I was able to crack the password in the properties file that @StoneNimRod provided, and it sounds like the data was safely recovered :)
