### ISSUE TITLE
adb -> udb

### ISSUE THREAD

**Issue by Breaktackle** [thenickdude/PlanC#21]
Hello there,

This is a great tool and looks very promising, thank you for putting forth all the effort.

I had my Crashplan migrated to the small business version a while ago, and the company had run a pilot program of shipping hard copies of the data backups, but encrypted as they are on the servers.  I had continued paying for the service and let it go a little too long, but I was thinking when I had time I would be able to tackle a drive restore at some point.

I followed the provided instructions and attempted to hook this backup volume to my account, and despite the software settings to not do maintenance on the archive, within 24 hours the archive started doing maintenance and deleting old files (which are the entirety of the backup).  Fortunately I had the forethought to run a Macrium Reflect backup on the drive so I still have the data despite it getting wiped by the app.

I am going to dual boot linux and attempt to try this on this coming weekend. but I noticed that the adb folder has been renamed to udb.  It looks like the contents of the folder are very similar to the adb folder so I'm thinking I will just be able to change the reference commands.  I will attempt to restore the local backup and crossing my fingers that it goes as intended.

**Comment by thenickdude** [comment]
I'm interested in adding support for their Small Business version too, so let me know how you get on! 

If it doesn't work then please email me a copy of your "udb" directory and also the "cp.properties" file from the backup archive folder so I can see how it's structured in that newer version, n.sherlock@gmail.com . Note that these files will disclose your account email address, and (potentially) your account password and decryption key to me.

Make sure to make a backup copy of that udb directory, since when PlanC opens that database it causes it to replay any database transactions that were in-progress when the backup software was shut down, which could corrupt the database if it was created with a newer version of the database software.

**Comment by thenickdude** [comment]
I can see why PlanC was unable to unlock your udb directory, in this new version CrashPlan uses Windows' encryption functions to protect that data, and this requires it to be unlocked on the same machine it was locked on. In the old Home version it just always used the same password on every computer to lock the udb directory, so it could be decrypted by anybody.

I'll try adding support for that to PlanC for you.

**Comment by thenickdude** [comment]
I'm making progress, I was able to unlock the (empty) udb directory that installing CrashPlan on my computer created, but since I don't have a CrashPlan account I wasn't able to see how the archive decryption key is stored.

I'll sign up for a CrashPlan trial so I can figure it out.

**Comment by thenickdude** [comment]
Bad news, CrashPlan Small Business *does* use an ADB directory, and that's where the archive decryption key is stored. Are you sure you don't have an adb directory?

Probably you're logged out of CrashPlan? It deletes the ADB directory when you log out.

You should be able to log back in to CrashPlan (on any computer) and have it create the ADB directory for you.

The good news is that Plan C turns out to be compatible with the CrashPlan Small Business backup format already (I was able to restore a backup once I had recovered my key)

**Comment by thenickdude** [comment]
Probably you're logged out of CrashPlan? It deletes the ADB directory when you log out.

You should be able to log back in to CrashPlan (on any computer) and have it create the ADB directory for you.

**Comment by Breaktackle** [comment]
That is great news!  Thank you very much for investigating this issue.  Does this change the order of operations for decoding or is it still the same walkthrough as the main page using the ADB directory as the recovery option?

**Comment by thenickdude** [comment]
Still the same order, but wait a sec and I'll upload a new version of Plan C for Windows for you to use

**Comment by thenickdude** [comment]
Here's the new version:

https://github.com/thenickdude/PlanC/releases/tag/v0.3

Here's the readme for the new version:

https://github.com/thenickdude/PlanC/blob/win32-support/Readme.md

You'll need to stop the CrashPlan Small Business service like it says, then copy the adb directory out, then follow the new directions for recovering an ADB key from Small Business (using PsExec).

**Comment by Breaktackle** [comment]
Thank you, does the ADB directory only populate if you have a backup archive location tied to your account?  My account only has the cloud area attached to it right now, but this hard drive was a snapshot of the cloud from 2019.

**Comment by thenickdude** [comment]
In my test it was populated even though I have no backup destinations at all.

**Comment by Breaktackle** [comment]
It works!  At least the list command is working right now, and I am using the v0.3 Windows release.  I have yet to restore anything but I was worried with the LOCK file being 0 kb that there would be an issue, and worried that something would get overwritten reattaching the account to the computer.  I will attempt to perform the restore this weekend.  It looks like as long as the guid of the backup device is the same, regardless of account password changes, the encryption is the same.

**Comment by thenickdude** [comment]
Great news!

**Comment by thenickdude** [comment]
For restoring files use the new v0.3.1 release, it avoids including colons in filenames, which don't work on Windows

**Comment by Breaktackle** [comment]
Hi Nick,

Some of the restore files have the file name followed immediately by ':Zone.Identifier Unsupported File Type 2...".  Do you also have to run the restore operation with the ---include-deleted tag in order to capture everything?

**Comment by thenickdude** [comment]
That's a new one, I'll see if I can figure out what those are. What type of file are they attached to? 

You can use --include-deleted but it will then include files that were deleted at the time the backup was created. It can be a bit of a mess since with a 90 day deleted file retention period this will include 3 months of temporary files and other short-lived garbage. It won't change the "Zone.Identifier" situation

**Comment by thenickdude** [comment]
It looks like "Zone.Identifier" files are metadata files that Windows creates when you download files from the 'net, to record what website they were downloaded from so Windows can warn you when you try to open them that those were downloaded files:

https://github.com/microsoft/WSL/issues/4609

So they're just junk really, you can ignore those messages.

**Comment by Breaktackle** [comment]
One other point of note, I had backed up external hard drives to the account on certain drive letters that were remapped to flash drives at a later date. Running the --include deleted flag seems to be restoring the initial drive backup as well, so this might be helpful to folks that remapped drive letters during their Crashplan tenure.

**Comment by thenickdude** [comment]
Good point! Include deleted will include every file CrashPlan ever saw, until the deleted file retention period expired them.

**Comment by Breaktackle** [comment]
Still restoring the backup here, thank you for all your help!
