### ISSUE TITLE
Cannot restore Windows files

### ISSUE THREAD

**Issue by laszlokormoczi** [thenickdude/PlanC#4]
Filenames in a Windows backup start with a drive letter and a colon (_e.g._ "C:") and since `destFilename` is a simple concatenation of the destination directory and the original filepath (planc.cpp: line 258), this leads to an invalid filename (directory name) like "/destinationpath/C:/originalpath" and gives a `boost::filesystem::create_directories: Protocol error` error.

**Comment by OurDataNotYours** [comment]
This sounds like you have built and run Plan C on Windows, which is unsupported (it can create directories with colons in the name with no issue on Mac OS and Linux).

Can you let me know how you're building on Windows? (I don't do any Windows development myself, which is why I didn't release any Windows binaries or make it Windows compatible)

**Comment by matthewblain** [comment]
FYI I have successfully restored files using the Windows Subsystem for Linux on Windows 10. It's a bit clumsy, but Ubuntu on WSL on Windows works. It creates a directory "C:" in the Linux subsystem, which gets translated into C[someunicodecharacter] in Windows.

**Comment by audiolomb** [comment]
Ilike @matthewblain I was able to use the WSL to restore the files.
This was literally a life saver for me. I begged Code42 to help me past the sunset of the home edition and they refused to upgrade my account.

I can only say a BIG THANK you to the developers because they did an awesome job with this.

Just one question. Is it possible in any way to restore the original timestamp of the files?

**Comment by laszlokormoczi** [comment]
@OurDataNotYours sorry for not responding for a while, in fact I realized what was the problem a few hours after asking... I have used Plan C on a Linux VM, and a directory from the host Windows machine was shared to store restored files. So the directory name was invalid on the Windows side. Solved by creating the mount point in a manually created `C:` folder and setting `--dest` to the parent folder.
@audiolomb seems that current version cannot do this, but for a workaround you can use the `list-detailed` command, redirect the output to a file, and write a script that parses the file and modifies the file creation date with `touch`.

**Comment by audiolomb** [comment]
@laszlokormoczi -list-detailed shows the latest backup date, not the files' last modified date.
Thanks for the suggestion though!
